import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomCursor } from "@/components/ui/CustomCursor";
import { NoiseOverlay } from "@/components/ui/NoiseOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SmoothScroll } from "@/components/layout/SmoothScroll";
import { DynamicDock } from "@/components/layout/DynamicDock";
import Preloader from "@/components/ui/Preloader";
import { LogicCompanion } from "@/modules/ai-companion";
import { TransitionProvider } from "@/context/TransitionContext";
import { Shutter } from "@/components/layout/Shutter";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomCursor />
        <NoiseOverlay />
        <SmoothScroll>
          <TransitionProvider>
            <Shutter />
            {children}
            <DynamicDock />
          </TransitionProvider>
        </SmoothScroll>
        <Preloader />
        <LogicCompanion />
      </body>
    </html>
  );
}
