-- Add missing BotAlertType values for R22 sprint
ALTER TYPE "BotAlertType" ADD VALUE IF NOT EXISTS 'DOMAIN_NOT_AUTHORIZED_SPIKE';
ALTER TYPE "BotAlertType" ADD VALUE IF NOT EXISTS 'LEAD_CAPTURE_FAILURE';
